import type { Metadata } from "next";
import { KeyRound, Pencil, Plus } from "lucide-react";
import { ConfirmAction } from "@pathwayiq/ui/blocks/confirm-action";
import { FormDialog } from "@pathwayiq/ui/blocks/form-dialog";
import { EmptyState, Forbidden, FormField, PageHeader, StatusBadge } from "@pathwayiq/ui/blocks/page";
import { SecretDialog } from "@pathwayiq/ui/blocks/secret-dialog";
import { Badge } from "@pathwayiq/ui/components/badge";
import { Button } from "@pathwayiq/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@pathwayiq/ui/components/card";
import { Input } from "@pathwayiq/ui/components/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@pathwayiq/ui/components/table";
import { api, apiOrNull } from "@pathwayiq/api/iam";
import type { Permission, ServiceClient } from "@pathwayiq/api/iam-types";
import { createServiceClient, rotateServiceClientSecret, setServiceClientStatus, updateServiceClient } from "../_actions/clients";

export const metadata: Metadata = { title: "Service clients" };

export default async function ServiceClientsPage() {
  const [result, catalog] = await Promise.all([
    api<ServiceClient[]>("/api/v1/iam/service-clients"),
    apiOrNull<Permission[]>("/api/v1/iam/permissions"),
  ]);
  if (!result.ok) {
    return (
      <>
        <PageHeader title="Service clients" />
        <Forbidden what="service clients (GLOBAL iam.client.manage)" />
      </>
    );
  }
  const registered = (prefixes: string[]) =>
    (catalog ?? []).filter((p) => p.status === "ACTIVE" && prefixes.some((prefix) => p.code.startsWith(prefix + "."))).length;

  return (
    <>
      <PageHeader
        title="Service clients"
        description="Machine identities of other microservices. A service uses its client id and secret to get short-lived tokens, registers the permissions under its prefixes, and asks IAM for decisions."
        actions={
          <SecretDialog trigger={<Button><Plus /> New service client</Button>} title="New service client" submitLabel="Create"
                        action={createServiceClient}
                        description="The secret is generated by IAM and shown once.">
            <FormField label="Client id" htmlFor="c-id" hint="Lowercase letters, digits and '-', e.g. project-service">
              <Input id="c-id" name="clientId" placeholder="project-service" required pattern="[a-z][a-z0-9-]{1,99}" />
            </FormField>
            <FormField label="Name" htmlFor="c-name"><Input id="c-name" name="name" placeholder="Project management service" required /></FormField>
            <FormField label="Permission prefixes" htmlFor="c-prefixes"
                       hint="Comma-separated. The service may only register and check permissions under these, e.g. project → project.*">
              <Input id="c-prefixes" name="prefixes" placeholder="project" required />
            </FormField>
          </SecretDialog>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>{result.data.length} service clients</CardTitle>
          <CardDescription>Disabling a client stops new tokens immediately; issued tokens expire within 5 minutes.</CardDescription>
        </CardHeader>
        <CardContent>
          {result.data.length === 0 ? (
            <EmptyState>No service clients yet.</EmptyState>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Client</TableHead>
                  <TableHead>Prefixes</TableHead>
                  <TableHead>Registered permissions</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {result.data.map((c) => (
                  <TableRow key={c.id}>
                    <TableCell>
                      <span className="font-medium">{c.name}</span>
                      <span className="block font-mono text-xs text-muted-foreground">{c.clientId}</span>
                    </TableCell>
                    <TableCell className="space-x-1">
                      {c.prefixes.map((p) => <Badge key={p} variant="outline" className="font-mono">{p}.*</Badge>)}
                    </TableCell>
                    <TableCell className="tabular-nums">{registered(c.prefixes)}</TableCell>
                    <TableCell><StatusBadge status={c.status} /></TableCell>
                    <TableCell className="space-x-1 text-right">
                      <FormDialog trigger={<Button variant="ghost" size="sm"><Pencil /> Edit</Button>} title={`Edit ${c.clientId}`}
                                  action={updateServiceClient}>
                        <input type="hidden" name="id" value={c.id} />
                        <FormField label="Name" htmlFor={`n-${c.id}`}><Input id={`n-${c.id}`} name="name" defaultValue={c.name} required /></FormField>
                        <FormField label="Permission prefixes" htmlFor={`p-${c.id}`} hint="Comma-separated">
                          <Input id={`p-${c.id}`} name="prefixes" defaultValue={c.prefixes.join(", ")} required />
                        </FormField>
                      </FormDialog>
                      <SecretDialog trigger={<Button variant="ghost" size="sm"><KeyRound /> Rotate secret</Button>}
                                    title={`Rotate the secret of ${c.clientId}?`} submitLabel="Rotate"
                                    description="The current secret stops working immediately. Update the service's configuration right after."
                                    action={rotateServiceClientSecret}>
                        <input type="hidden" name="id" value={c.id} />
                      </SecretDialog>
                      <ConfirmAction
                        trigger={<Button variant="ghost" size="sm" className={c.status === "ACTIVE" ? "text-destructive" : ""}>
                          {c.status === "ACTIVE" ? "Disable" : "Enable"}</Button>}
                        title={`${c.status === "ACTIVE" ? "Disable" : "Enable"} ${c.clientId}?`}
                        description={c.status === "ACTIVE"
                          ? "The service can no longer obtain tokens; its calls to IAM fail once its current token expires."
                          : "The service can obtain tokens again."}
                        action={setServiceClientStatus} destructive={c.status === "ACTIVE"}
                        fields={{ id: c.id, status: c.status === "ACTIVE" ? "DISABLED" : "ACTIVE" }} />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </>
  );
}
